ranks:
    dirt3:
        name: Dirt III
        elo: 0
    dirt2:
        name: Dirt II
        elo: 530
    dirt1:
        name: Dirt I
        elo: 820
    wood3:
        name: Wood III
        elo: 1030
    wood2:
        name: Wood II
        elo: 1210
    wood1:
        name: Wood I
        elo: 1360
    stone3:
        name: Stone III
        elo: 1500
    stone2:
        name: Stone II
        elo: 1630
    stone1:
        name: Stone I
        elo: 1760
    iron3:
        name: Iron III
        elo: 1880
    iron2:
        name: Iron II
        elo: 2000
    iron1:
        name: Iron I
        elo: 2120
    gold3:
        name: Gold III
        elo: 2240
    gold2:
        name: Gold II
        elo: 2370
    gold1:
        name: Gold I
        elo: 2500
    diamond3:
        name: Diamond III
        elo: 2640
    diamond2:
        name: Diamond II
        elo: 2790
    diamond1:
        name: Diamond I
        elo: 2970
    emerald3:
        name: Emerald III
        elo: 3180
    emerald2:
        name: Emerald II
        elo: 3470
    emerald1:
        name: Emerald I
        elo: 4000